# Generated by Django 5.2 on 2025-05-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='wedding_date',
        ),
    ]
