# Generated by Django 5.2 on 2025-05-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_contactform_wedding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
