# Generated by Django 5.2 on 2025-05-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimalist', 'Minimalist'), ('themed', 'Themed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
