# Generated by Django 5.2 on 2025-06-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_invitationdesign_delete_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationdesign',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='invitations/'),
        ),
        migrations.AlterField(
            model_name='invitationdesign',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
