# Generated by Django 5.2 on 2025-06-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_invitationdesign_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationdesign',
            name='category',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('themed', 'Themed')], max_length=20),
        ),
    ]
