# Generated by Django 5.2 on 2025-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_invitationdesign_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationdesign',
            old_name='image_file',
            new_name='get_image',
        ),
        migrations.AlterField(
            model_name='invitationdesign',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationdesign',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
